name: Sync D1 Database

on:
  workflow_dispatch:  # Manual trigger
  push:
    paths:
      - 'actor-game/public/*.db'

jobs:
  sync-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Install Wrangler
        run: npm install -g wrangler
      
      # Generate migrations
      - name: Generate migrations
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: python sync_d1_database.py generate-migrations
      
      # Apply migrations - specify path to wrangler.toml if needed
      - name: Apply migrations
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          # If wrangler.toml is in the repo root:
          wrangler d1 migrations apply actor-to-actor-db --remote
          
          # Or if wrangler.toml is in a subdirectory:
          # cd actor-to-actor-api && wrangler d1 migrations apply actor-to-actor-db --remote