# GitHub Actions workflow file: .github/workflows/update-actor-map.yml
# This would run weekly to update the actor connection map

name: Update Actor Connection Map

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:     # Allow manual triggering

jobs:
  build-actor-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure we have all databases
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas networkx tqdm sqlite3 firebase-admin
          
      - name: Build actor connection map
        run: python build_actor_map.py
        
      - name: Commit and push updated connection database
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/actor_connections.db
          git commit -m "Update actor connection map [skip ci]" || echo "No changes to commit"
          git push