# GitHub Actions workflow file: .github/workflows/update-actor-map.yml
# This would run weekly to update the actor connection map

name: Update Actor Connection Map

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight (day after data update)
  workflow_dispatch:     # Allow manual triggering

permissions:
  contents: write  # This gives the workflow permission to write to repository contents

jobs:
  build-actor-map:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure we have all databases
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pandas networkx tqdm
      
      - name: List directories
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la
          echo "Files in actor-game/public (if exists):"
          mkdir -p actor-game/public
          ls -la actor-game/public || echo "Directory not found"
      
      - name: Ensure directories exist
        run: |
          mkdir -p actor-game/public
      
      - name: Build actor connection map
        run: python build_actor_map.py
      
      - name: Verify output file
        run: |
          # Check if the file was created in the expected location
          if [ -f "actor-game/public/actor_connections.db" ]; then
            echo "✅ Connection database created successfully"
            ls -la actor-game/public/
          else
            echo "❌ Connection database not found, checking alternative locations"
            find . -name "actor_connections.db" -type f -print
            # Exit with error if file isn't found anywhere
            find . -name "actor_connections.db" -type f | wc -l | grep -q "0" && exit 1 || echo "Found in alternate location"
          fi
      
      - name: Commit and push updated connection database
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Use the correct path to where the file is actually created
          git add actor-game/public/actor_connections.db
          git commit -m "Update actor connection map [skip ci]" || echo "No changes to commit"
          git push