name: Update Actor Data

on:
  schedule:
    - cron: '0 2 * * 0'  # Runs at 2 AM every Sunday
  workflow_dispatch:      # Allows manual triggering
    inputs:
      max_pages:
        description: 'Number of pages to process (max 200000)'
        required: true
        default: '1000'
        type: number
      update_default:
        description: 'Save this value as the new default?'
        required: true
        default: false
        type: boolean

jobs:
  update_data:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 hour timeout
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pycountry
          
      - name: Restore checkpoint if exists
        uses: actions/cache@v3
        with:
          path: ./actor-game/public/checkpoint.json  # FIXED
          key: ${{ runner.os }}-checkpoint-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-checkpoint-
            
      - name: Run data update script
        run: python update_actor_data.py
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_MAX_PAGES: ${{ github.event.inputs.max_pages || '1000' }}
          UPDATE_DEFAULT: ${{ github.event.inputs.update_default || 'false' }}
          
      - name: Save checkpoint for next run
        uses: actions/cache/save@v3
        if: always()
        with:
          path: ./actor-game/public/checkpoint.json  # FIXED
          key: ${{ runner.os }}-checkpoint-${{ github.run_id }}
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .  # Add all changes instead of a specific directory
          git commit -m "Update actor data" || echo "No changes to commit"
          git push
          
      - name: Check if data collection is complete
        if: success() || failure()  # Run this step regardless of previous step result
        run: |
          if [ -f "./actor-game/public/checkpoint.json" ]; then
            COMPLETED=$(python -c "import json; print(json.load(open('./actor-game/public/checkpoint.json'))['completed'])")
            if [ "$COMPLETED" != "True" ]; then
              echo "Data collection is incomplete. Triggering another workflow run."
              curl -X POST \
                -H "Authorization: token ${{ secrets.GH_WORKFLOW_PAT }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/update-data.yml/dispatches \
                -d '{"ref":"${{ github.ref }}"}'
            else
              echo "Data collection is complete."
            fi
          else
            echo "Checkpoint file not found, cannot determine completion status."
          fi
      
      - name: Update default value if requested
        if: ${{ github.event.inputs.update_default == true }}
        run: |
          echo ${{ github.event.inputs.max_pages }} > actor-game/public/default_pages.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add actor-game/public/default_pages.txt
          git commit -m "Update default page count to ${{ github.event.inputs.max_pages }}" || echo "No changes to commit"
          git push
