name: Update Actor Data

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Grant write access for pushing changes

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pycountry pandas

      - name: Update actor data
        id: update
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python update_actor_data.py
        continue-on-error: true

      - name: Check completion status
        id: check_status
        run: |
          if [ -f actor-game/public/checkpoint.json ]; then
            COMPLETED=$(jq -r '.completed' actor-game/public/checkpoint.json)
            if [ "$COMPLETED" == "false" ]; then
              echo "Process not complete, scheduling next run"
              echo "needs_rerun=true" >> $GITHUB_OUTPUT
            else
              echo "Process completed successfully"
              echo "needs_rerun=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No checkpoint file found"
            echo "needs_rerun=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add actor-game/public/
          git commit -m "Update actor data [skip ci]" || echo "No changes to commit"
          git push

      - name: Re-run workflow if needed
        if: steps.check_status.outputs.needs_rerun == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update Actor Data
          token: ${{ secrets.GITHUB_TOKEN }}
