name: Update TMDB Actor Data

on:
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Data Update Script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python update_actor_data.py

      - name: Commit and Push Updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add actors_data.json
          git commit -m "Automated update of actor data [skip ci]" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.MY_PAT }}@github.com/RileyBerycz/ActorToActor.git
          git push
      
