name: Upload to Firebase

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: read  # Only need read access to the repo

jobs:
  upload-to-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin

      - name: Upload SQLite data to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python force_github_databases_to_firestore.py